version: '3.3'

services:

  web:
    image: nginx:1.19.1-alpine
    ports:
      - 8080:80
    deploy:
      replicas: 3
    restart: always
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    # volumes:
    #   - ./db:/var/lib/postgresql/data
